name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python '3.13'
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: |
             python -m pip install --upgrade pip
             python test.py

        

